<Project Sdk="Microsoft.NET.Sdk">

   <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>

      <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
      <PackageId>WelterKit.Extensions.SystemCommandLine</PackageId>
      <Version>$(VersionPrefix)$(VersionSuffix)</Version>

      <Authors>Eric Tolman</Authors>
      <Description>Extensions for System.CommandLine methods to facilitate a functional approach via method chaining.</Description>
      <Copyright>Copyright (c) 2025 Eric Tolman</Copyright>
      <PackageLicenseExpression>MIT</PackageLicenseExpression>
      <PackageProjectUrl>https://github.com/cyranothedaft/WelterKit</PackageProjectUrl>
      <Title>WelterKit Extensions for System.CommandLine</Title>
      <RepositoryUrl>https://github.com/cyranothedaft/WelterKit.git</RepositoryUrl>
      <PackageReadmeFile>README.md</PackageReadmeFile>
   </PropertyGroup>

   <ItemGroup>
      <None Include="..\..\README.md">
         <Pack>True</Pack>
         <PackagePath>\</PackagePath>
      </None>
   </ItemGroup>

   <ItemGroup>
      <PackageReference Include="System.CommandLine" />
   </ItemGroup>

</Project>
